create table
  public.users_data (
    user_id serial,
    username text not null,
    auth text not null,
    token text not null,
    constraint users_data_pkey primary key (user_id),
    constraint users_data_username_key unique (username)
  ) tablespace pg_default;

create table
  public.work_data (
    work_id serial,
    work_admin_id integer null,
    urn text not null,
    auth text not null,
    display text null,
    constraint work_data_pkey primary key (work_id),
    constraint work_data_work_admin_id_fkey foreign key (work_admin_id) references users_data (user_id)
  ) tablespace pg_default;

create table
  public.members_data (
    work_id integer null,
    member_id integer not null,
    role text null,
    id serial,
    constraint members_data_pkey primary key (id),
    constraint members_data_member_id_fkey foreign key (member_id) references users_data (user_id),
    constraint members_data_work_id_fkey foreign key (work_id) references work_data (work_id)
  ) tablespace pg_default;

create table
  public.exams_data (
    exam_id serial,
    work_id integer null,
    display_name text not null,
    visibility text null,
    constraint exams_data_pkey primary key (exam_id),
    constraint exams_data_work_id_fkey foreign key (work_id) references work_data (work_id)
  ) tablespace pg_default;

create table
  public.sessions_data (
    session_id integer generated by default as identity,
    user_id integer not null,
    exam_id integer null,
    status text null,
    constraint sessions_data_pkey primary key (session_id),
    constraint sessions_data_exam_id_fkey foreign key (exam_id) references exams_data (exam_id),
    constraint sessions_data_user_id_fkey foreign key (user_id) references users_data (user_id)
  ) tablespace pg_default;

create table
  public.questions_data (
    question_id serial,
    exam_id integer null,
    type text not null,
    content text null,
    description text null,
    question_order integer null,
    constraint questions_data_pkey primary key (question_id),
    constraint questions_data_exam_id_fkey foreign key (exam_id) references exams_data (exam_id)
  ) tablespace pg_default;

create table
  public.options_data (
    option_id serial,
    question_id integer null,
    content text null,
    exam_id integer null,
    option_order integer null,
    constraint options_data_pkey primary key (option_id),
    constraint options_data_exam_id_fkey foreign key (exam_id) references exams_data (exam_id),
    constraint options_data_question_id_fkey foreign key (question_id) references questions_data (question_id)
  ) tablespace pg_default;

create table
  public.answers_data (
    answer_id serial,
    user_id integer null,
    exam_id integer null,
    question_id integer null,
    selected_option_id integer null,
    text_answer text null,
    constraint answers_data_pkey primary key (answer_id),
    constraint answers_data_exam_id_fkey foreign key (exam_id) references exams_data (exam_id),
    constraint answers_data_question_id_fkey foreign key (question_id) references questions_data (question_id),
    constraint answers_data_selected_option_id_fkey foreign key (selected_option_id) references options_data (option_id),
    constraint answers_data_user_id_fkey foreign key (user_id) references users_data (user_id)
  ) tablespace pg_default;

create table
  public.results_data (
    result_id serial,
    user_id integer null,
    exam_id integer null,
    score integer null,
    constraint results_data_pkey primary key (result_id),
    constraint results_data_exam_id_fkey foreign key (exam_id) references exams_data (exam_id),
    constraint results_data_user_id_fkey foreign key (user_id) references users_data (user_id)
  ) tablespace pg_default;

  create table
  public.realtime_pages (
    id bigint generated by default as identity,
    work_id integer null,
    exam_id integer null,
    access text null,
    constraint realtime_pkey primary key (id),
    constraint public_realtime_pages_exam_id_fkey foreign key (exam_id) references exams_data (exam_id),
    constraint public_realtime_pages_work_id_fkey foreign key (work_id) references work_data (work_id)
  ) tablespace pg_default;